### ISSUE TITLE
What is the license of source code in this repository?

### ISSUE THREAD

**Issue by soimsoim** [marytts/jsptk#6]
Dear @seblemaguer , @psibre,
What is the license of source code in this repository?

In the following link, the license is under LGPL-3.0. Is this information correct?
https://bintray.com/marytts/marytts/jsptk

Would you tell me if I can include this source code in a commercial product?

Please tell me what the license is.

**Comment by seblemaguer** [comment]
Hello,

same than for jworld, it is actually a BSD-3 license. Everything is updated accordingly.
